#workflow:
#  rules:
#    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#      when: always
#    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#      when: always
#    - if: $CI_COMMIT_TAG
#      when: always
#    - when: never

stages:
  - build
  - sast-scan
  - build-and-sign-image
  - container-scan

include:
  - component: gitlab.com/components/sast/sast@2.1.0
    inputs:
      stage: sast-scan
#  - component: gitlab.com/components/container-scanning/container-scanning@4.2.0
#    inputs:
#      stage: container-scan
#      cs_image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_ID}"

build:
  image: node:23.4.0
  stage: build
  script:
    - npm install
    - npm run build
  allow_failure: false

sign-image:
  stage: build-and-sign-image
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    COSIGN_YES: "true"
    DOCKER_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_ID}"
    DOCKER_IMAGE_LATEST: "${CI_REGISTRY_IMAGE}:latest"
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  timeout: 20 minutes  # Add timeout to prevent infinite hangs
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - "# echo GITLAB_CLIENT_ID is ${GITLAB_CLIENT_ID}"
    - "# echo GITLAB_REDIRECT_URI is ${GITLAB_REDIRECT_URI}"
    - |
      docker build --pull \
        -t "$DOCKER_IMAGE_NAME" \
        -t "$DOCKER_IMAGE_LATEST" \
        --build-arg VITE_GITLAB_CLIENT_ID="${GITLAB_CLIENT_ID}" \
        --build-arg VITE_GITLAB_REDIRECT_URI="${GITLAB_REDIRECT_URI}" \
        --build-arg NODE_OPTIONS="--max-old-space-size=4096" \
        --progress=plain \
        .
    - docker push "$DOCKER_IMAGE_NAME"
    - docker push "$DOCKER_IMAGE_LATEST"
    - apk add --update cosign
    - IMAGE_DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' "$DOCKER_IMAGE_NAME")"
    - echo "$IMAGE_DIGEST"
    - COSIGN_EXPERIMENTAL=1 cosign sign --registry-referrers-mode oci-1-1 "$IMAGE_DIGEST"
